language: c
sudo: required
dist: trusty
services:
  - docker

# Don't build the pyup- branches that pyup.io creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^pyup-/

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
      - secure: "Z7bsDMYdKZCN5JQCRgL3DPksoOXNm1uqoeDfPXw/X77fjnUoWE1KOXBFUKqEypyiAGpkNQsvjdJ/n3bNw+aG74GZMqFCvvk4/Lt6zXA0KLpc+fZkul9rkEaQQ3+kDbJuaUXDRTAq56ZOGLDHPOI5at/DFzF3keQuHp9VguekmZ2NeWfJQFPKXadv69zmVZeMMA3AVAFoyAvxCY2X/ZQJ/VukjN4nBkeM0Ph/Tdbypy+QerqnNfarqebWpnrYeAA6HxRl/+YH+OxSGHsT/iw73UxNpqFI2BB7nMQRBXgPe4J1BcgVwJ90V13YbdG4ICojlydGTSOEyuxRTuaTPDyscX2O8xap7ffnJFvY3ueu07bbbO75VOfOPyqbN4FfNj9qqH3A8wG0pe9L2G/XVSgo2wUO9iN9VWy6bXQhUUG/KedsBm8EBXi0yncDo120xmnMJ5vSEPbWJ5OILZcJbjSdyWWTISdpbmdPwX+DNwa2pwkS0mcM1u+yyGDE5vUT8XJVmv+r5DuqUHduDy8Bllh2vP4h+UUJu5j9X82M4eDg9G0xiuvwzAiovO/5R+g4aCDwaIApBwGoZnpKI7dQTl3onYSDY0XaVzNPWpGzzCbtZVyCW7LjewUoGJ3P5azf6zUOaOt9SJDoA2F3gbC15xJAgp8JutZ1bUeMrjdJqq1NGfM="
      - secure: "c8j6/fl1ree3tbzpkfagpzu2Sq5EXk/bJeQXUXz7i9v7mcVmbuh91b9Yn9VwAi6BMqlXgv3ylLW9AAf4m6UxXIEPgN4GQuqfvC5qbqexKcB+qgk1bftcGxhkOQQTQQhzK8777D7UC0eMWlaPiaLX+TxAnKZGwe/fInsqTOoPyZsN8KTFl3hN9my8C3JnmgwP6mgiL0m6YuOttS7tIvOCYDlt8IWxQ+AyInBcMops9pE6IkiBcPY6ni7SM8SVuv8rnvMEemMRjKhCQ4eGqeVRIMkFRxE4CSIg2LIis8athbuLBUWNHAjR1/lSIz90a20M53RjiMMMCiY4VkB0hP+1RxUcQfw1z2NfY0hgZwi4hzYdSEWcw5HoSYb1EHugprTObvVBeXKxr62FZIa2GJu36HubuuqBTpXsT+CLFTD4m6ZvcpDTELismvOhcuhUf+Md3wt7AL7vll9Dd0O7JQYkSn5b2gaea/PY6KaOT5p02YMhnxSrBAUMnVp3fkQnZnEpneQUOb2+DOwxB/KqfmhIBGRtyP4YpI4gdnfVlC4yBePlzKj4CuQQ8AiSziffwOSeUC1v1mxXlkbZ2mxzkF3DXuRMtWiQuDcZYKhc9rrIF8SM1VpvWBvesdvpGhT+szCk35XikpqlkUmztEx80B06m4sPawmEBrpr0u9/cn0Pw9M="
    # HUB_USERNAME and HUB_PASSWORD
      - secure: "v0x35lVVuMcPy0ElWl9+cJJroyGpjzS9TqDwg8z3ps47xE8hi6xw018+3AlF/EAdenQxjB6dAEFYdJFpqKkAN3zuyONaC3dBsRfbS/Y8LXtVCs2AZZIpbn8VgNbLoeV1eEZmltDML4FGW2634k/b7najUUli9QGKfXvo8rSazPm/GqCGYJM3c0vuCQO66LoTwwaW7eg3pBriHKN/cc2GXBsawkvoQ0yLyH1bhcEcDcYk4H7U8in0xxWc5YOIEH7wRK6pRHwtew3CcDw+s627EkyOLqMCtUzax4CRh+SlMTXYHcgPm5W6raGXqutm3OfHdueCWDzWoxrxloC/6Hg8g14tQamkKeB0yNvBPGt/OWbIoSE2KTPd1LVNhAT3BzA4FmeAE8OkcMvKDrs78yjyXtdymNL4knQvYoVrw3mgWRpuymmFPk8vemnyOem2vChye0ZuuJ6kbW+2e1qzSE9bGI6f6rcV09GU5MVXLB9hFp7VcEBab5Wd0T+/ypQreM14PRy7DcIHX9xQpQmGPCW6BVnDvOZHDmZ57jZwUPioI8HQinBhcK+leTlOJtlp/kx0qbSPCFIvmjJFY6nukde4I3AxY40IojI4DJCC/XT3ENt4Tz9uNX6jdsGyALgkwk3ArB0uPR3gSovQu0lfZfaUBi7L014+OBeU72Fxr52iw8o="
      - secure: "roGF9inQ20raN8gs52Sd0hRkXVWguuGKxcPSDaXPMLi+IZ50axSqFchJdj2a9CAhwuHC1rXiDUvl9e8+5qAywM29n55c9Vz63YByVZ9xfjYjzBUrMmjryqPR/RijllauSb0P/fuPZ/l32ssY1eUHLVqpr2BovdI86QGqXArOnEhlfq1OKeGFDPEGat8EAq1STeu9CUpI2o17Oivq7CN3LqdpgzOTaPiAUD3Tu4ms/VW/qmTGF78gnLy//klhEgtyEyideX7SyvpnW/q+0nFUBNWF8pGhU/zprcHxmHxMyy4viQq9/pxYdjH3GznuXFT98izo3uuvy6OpuwLmZYmA6G4HpAcbG5KBMD3l8PfeFFWfMDQoLBkmazMYan0fLI4zSPTfjA8UUYmD2r/OSVMipbxu/uKqkaMA26/7dUytOAesLROeDcIp6Y/HRtmUcKAOrhYsSvqw6upLJCCs2Aj2UXS4fmYUzXX8XEsLNpnfDfk/azenNipZuHLp4bCcdCILoy9xnVgf1R7XfqEhor+I897KkHXrpz0Jb5oqc7vKSmWCRgy9GvV6ERnFhWXPtLbiW784NNO4n4lZf2MZJpziZuol3NQBGZ/PW+uFEMgaNa+JQsOlOkNK9dY6T4jhOitjlJ7VNRl2wwjSJeBL47y2AFEAIZtGO2L/cvHdD8Z0VkE="


matrix:
  include:
    - env: PLATFORM="i686"
    - env: PLATFORM="x86_64"

script:
  - bash ./docker/build_scripts/prefetch.sh openssl curl
  - docker build --rm -t natefoo/manylinux1_$PLATFORM:$TRAVIS_COMMIT -f docker/Dockerfile-$PLATFORM docker/


deploy:
  provider: script
  script: docker/deploy.sh
  on:
    branch: libpython
