language: c
sudo: required
dist: trusty
services:
  - docker

# Don't build the pyup- branches that pyup.io creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^pyup-/

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
      - secure: "DLaNPUOPZ6rBTWSVRZIz+l4iPLK5jXFXzEa/yyRGQAJIm7ZjUsarpXaO1q7m4ZHOnIbM3n7Fih49xG3NNQvaX3Xo/LLdvxMpesDz3Oywnj+iE3HV+x6rvAgW8FVUOGYgCEFUIv9OuBNRDMe5EZ7qc8aivkA4CghjOur52T1rN0hS0D6mEE2ACYmZ0NRD9iHcO0wV509/G0BSoZKAuCumaM9nKTNMaHtsKEohJ9tH5zbOmezmT/CyxRnJRyVviWP2m8xo2njKEvp4qhro8OfHzwgnSUl0w8vcxiLhdwcSF08rG4kj8uEtwRcU2ROaybm4FFXXfDbzydUV99BRqRJTuLuce1UEiMoDeEep0oNBxKsWlVzZ5jNj6jOfnUL7VqPhIfI4b8L/iy0JL1fo9OkY7VmlbBHYwHqU2IxW3r+oGsB7WC50E2Pyci3kpCVC39oXxkAUiG55PPMhUtuSVBa6rk1L+PG7T8HqsfrYpB3sZeyE8UXeULwkQQf8TZSECsaM1mzqtaHOhJCPJmiKwOvLhnaXwRnTD7iwvDste8VZvWLmIE6IMgwUuT3O140k3HgXed6tWQs+UvECm99aJeW/uC7v7XJKlAwDsM5i5hf9IZLW/tIjCAbp3ssmOub89eLMxYwc9906TMRKbMM8RP9epbHhRFSuR2dO1f98MPPMtjQ="
      - secure: "WKPO9JLiH/UGXMRpWp7Hx2/kWQ7FcHG/pRQv6j2i1tNyrJTrzg88xLkuJDJUih7djxHWhur2UZId0j3lJljfWobX2tRHsvhONDm5UmvjjPMxb8Su2/tvbNHI7NCUOa2QHfOTXMoJlBACqZC2DObazvlrMOSB3O/gj6QkpclMIvSHmOa2J2ZGR5inym6igJy3WgNl1pz8liHT4sPk2LNxI94kC+pLj/zTF4NAbsVBOJaobRAPivayz49A3cC/hs+oADJ7aCF2bGgVa1flTe7OBoKITxWYikh7Tbe4aWhAuYssn6YEoFuy9V3DhZ5CHSR3M40YBL1TEfoB7g6wRFwwqzNr0Upw2dBE7vbqpt4vPxJkPbJ6GeJWf/gLtb2FEjidr3ygstWP3hShMLiK0YzqDBgRwDRXDg4pC0N5RYSakVGNZ/vHs9jxawgjV+4Gs2b4SQFCVrR7CFm3Q/S9Tioz15ICeMFYmUW029lLStK6pgJqobD2bDIMdQEs68EMT3S0ozHacOdJFKDBr1RDNaR/TQFh/BHEl55qHVhesrNkFqJi9UQCqKVkJ5eesvJ9+QZ6sKGGSHy2rU5i++rZa6u57dStU+9o8aG3vqvVbotINOpxdOtIx+USoc0Iz8QK87ywyYl5fsGqm1rE/6YZOtHYtHPjNUdEmenN91Fv7d+ix/g="
    # HUB_USERNAME and HUB_PASSWORD
      - secure: "ISAvca442p8cLDStiB59q5lH6jkrZN8ybtroyc7PbaThKsgLIBWvdv9PzoW1zewkZNDq5+U9+3iDUimkJBUSrLH2LNe4jSzGqgFmE6GT7ptSxjDxmMI9OQAUgyJQL4K83pvb/Ixh0h5FUXS/wjPWSnnXw1c+iIL7q/Lp7yF54UGHfp4fPGdHHEXoz50JWmeZgbTUdKEQPtm8rjXSJkzy8atJzCmRwQHFhLFA+Ncb00ZYo+x1nMLl46MXUzdqS7p0D5miqVzrpY/WxSKWMoFOT0mNo4XRyE7CvRQ8rmaD7On0BUkPuA2zhe/rbCcN0lc5D4G5GjPPO0/pOp5yMR9jtmDG4mQDyfVf7I1nVPeVP/kLTY6JrTjwNhXAj81FLP+mcC4f7ZVkZWsl/reC5/JnQnIIXjSFTAnGy2zE5dFAtD23oQyuLN9Bin7MfriUEAO0pTfaSAPNAsz+Jf6lhIfnPUm5giz3BraoSQnMdx3akG+EfQ/fi5z0vUQGM7ZGmMuHdHcl91anElIskXbVxJT07eqGBDBBV6N0hNpDRrApWsOYISkxAEn29Caq/Z1A0fsCtgtRBkXE2EvYEB2DEva5tDxxz4PBGV32H2IseVSitgR4AFoZ10l4GTwWf/ld88bSUs1OBcsr6RYXNSq6aX74+fiEsPiC2XB669r3vrdv658="
      - secure: "t35GFCPJF9H2uebq/xQnP/aQY6YH8ZEixPO60Z3SMF0B31Hw94kQD4dxZbucdHyly5sv2yCMYnlz3Xz7f2T+o8dNGeViUohrwlGXEHHGm5hkzKccQK3Q+D+TK1sWS/rbfDqSZZp5/Q0M55LnZ9isYxXNXvGMC9S06GrhurvZ7PRvJjFFDDfIYAmwtU4BN2mKn7j8Jc3omfI01Eeh2QxB4SSwngArVcYfpcjpwpq41Bo/5PooXJXFTnnWaF4CQTodFQGhHc8LaPzz6moaiGtWoZx3nKYBzUMbxCWe/mtsMnpqPQxOxxWnwCkDrBW9VMDD95u4Lo0/OqsaOm31bnF0Nd+uCD3xM16nWm0sq1nsevH7zM6w3KUFPseHYWCYLGAtDL6S5E0afbIEDWAaLBnB5uEEVfhGDKUaXSZGHkeOfpI6bxUU7x8Csj4d0ayGbrzTEggNxclUStvZ4S24DjnskGZ4vVsnooHgeaTTJvVBRCHaILx6O0aoDd9DswDTZlHa4f/H6uThVChqHb3TXTtUYKmGnnQ9AREKSAXsrPxCvNkfUIBl7FkpsDawfSWZr2E9ipykyfSzBkC4VFcZIZjGIMBoYSDfv++ht/yNjmH/haQnhrvUXh2UpryBPXHyxSoN1lqfVjQGKVsd23ZsjTOc8UQDQ+J1Ot/8vb1whFpnjB4="


matrix:
  include:
    - env: PLATFORM="i686"
    - env: PLATFORM="x86_64"

script:
  - bash ./docker/build_scripts/prefetch.sh openssl curl
  - docker build --rm -t natefoo/manylinux1_$PLATFORM:$TRAVIS_COMMIT -f docker/Dockerfile-$PLATFORM docker/


deploy:
  provider: script
  script: docker/deploy.sh
  on:
    branch: libpython
